apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: scb-rag-demo
  labels:
    app: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app: backend
