apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: scb-rag-demo
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: frontend
