# 生产环境 Kubernetes 部署配置
# 包含性能调优建议：
# - 资源请求和限制优化
# - 自动扩缩容（HPA）配置
# - 健康探针配置
# - 优化的 JVM 参数

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
  labels:
    app: spring-boot-demo
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-demo
  template:
    metadata:
      labels:
        app: spring-boot-demo
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: app
        image: spring-boot-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: spring-boot-demo-secrets
              key: database-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: spring-boot-demo-secrets
              key: database-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-boot-demo-secrets
              key: database-password
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        # 性能调优：根据实际负载调整资源请求和限制
        # requests: 保证的最小资源
        # limits: 允许的最大资源
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: spring-boot-demo-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-service
  labels:
    app: spring-boot-demo
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-boot-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-demo-config
data:
  application.yml: |
    spring:
      application:
        name: spring-boot-demo
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            format_sql: false
        open-in-view: false
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          probes:
            enabled: true
          show-details: when-authorized
    logging:
      level:
        com.java.demo: INFO
        org.springframework.web: WARN
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-demo-secrets
type: Opaque
stringData:
  database-url: "jdbc:postgresql://postgres-service:5432/spring-boot"
  database-username: "spring-boot"
  database-password: "change-me-in-production"
---
# 性能调优：自动扩缩容（HPA）配置
# - 基于 CPU 和内存使用率自动调整副本数
# - CPU 目标：70% 平均利用率
# - 内存目标：80% 平均利用率
# - 副本范围：3-10
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-boot-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-boot-demo
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # CPU 达到 70% 时触发扩容
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # 内存达到 80% 时触发扩容
  # 扩缩容行为策略
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 缩容前等待 5 分钟稳定
      policies:
      - type: Percent
        value: 50  # 每次最多缩容 50%
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0  # 立即扩容
      policies:
      - type: Percent
        value: 100  # 每次最多扩容 100%
        periodSeconds: 30
      - type: Pods
        value: 2  # 或每次增加 2 个 Pod
        periodSeconds: 30
      selectPolicy: Max  # 选择扩容幅度最大的策略
