apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: spring-boot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "http://localhost:30080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: spring-boot-demo
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  namespace: spring-boot-demo
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
