apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spring-boot-demo

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - ml-service-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: spring-boot-demo
  app.kubernetes.io/managed-by: kustomize