apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: spring-boot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: ml-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: spring-boot-demo
spec:
  selector:
    app: ml-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
