apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: scb-rag-demo
  labels:
    app: postgres
data:
  init.sql: |
    -- 创建文档表
    CREATE TABLE IF NOT EXISTS documents (
        id BIGSERIAL PRIMARY KEY,
        filename VARCHAR(255) NOT NULL,
        original_filename VARCHAR(255) NOT NULL,
        file_path VARCHAR(500) NOT NULL,
        file_size BIGINT NOT NULL,
        content_type VARCHAR(100),
        status VARCHAR(50) NOT NULL,
        upload_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        process_time TIMESTAMP,
        error_message TEXT,
        metadata JSONB,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- 创建文档块表
    CREATE TABLE IF NOT EXISTS document_chunks (
        id BIGSERIAL PRIMARY KEY,
        document_id BIGINT NOT NULL,
        chunk_index INTEGER NOT NULL,
        content TEXT NOT NULL,
        embedding VECTOR(1536),
        metadata JSONB,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
    );

    -- 创建查询历史表
    CREATE TABLE IF NOT EXISTS query_history (
        id BIGSERIAL PRIMARY KEY,
        query_text TEXT NOT NULL,
        query_mode VARCHAR(50) NOT NULL,
        response_text TEXT,
        source_documents JSONB,
        execution_time_ms BIGINT,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        user_id VARCHAR(100),
        session_id VARCHAR(100)
    );

    -- 创建索引
    CREATE INDEX IF NOT EXISTS idx_documents_status ON documents(status);
    CREATE INDEX IF NOT EXISTS idx_documents_upload_time ON documents(upload_time);
    CREATE INDEX IF NOT EXISTS idx_document_chunks_document_id ON document_chunks(document_id);
    CREATE INDEX IF NOT EXISTS idx_query_history_created_at ON query_history(created_at);
    CREATE INDEX IF NOT EXISTS idx_query_history_user_id ON query_history(user_id);

    -- 为向量搜索创建索引（如果使用 pgvector）
    -- CREATE INDEX IF NOT EXISTS idx_document_chunks_embedding ON document_chunks USING ivfflat (embedding vector_cosine_ops);
