spring:
  application:
    name: spring-boot-demo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring-boot}
    username: ${SPRING_DATASOURCE_USERNAME:spring-boot}
    password: ${SPRING_DATASOURCE_PASSWORD:spring-boot}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cache:
    type: redis
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,httpexchanges,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com.java.demo: INFO
    org.springframework.web: INFO
