spring:
  application:
    name: scb-rag-demo
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:scb_rag_demo}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  # Redis configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1 hour
      cache-null-values: false
  
  # File upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_FILE_SIZE:10MB}
      file-size-threshold: 2KB
  
  # Jackson configuration
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# Server configuration
server:
  port: ${BACKEND_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-message: always
    include-binding-errors: always

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Springdoc configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true

# Application custom configuration
app:
  # Poe API configuration (OpenAI compatible format)
  poe:
    api-key: ${POE_API_KEY}
    base-url: https://api.poe.com/v1
    model: ${POE_MODEL:Claude-3.5-Sonnet}
    timeout: 30000
    max-tokens: 4000
    temperature: 0.7
    max-retries: 3
  
  # RAG configuration
  rag:
    chunk-size: ${CHUNK_SIZE:500}
    chunk-overlap: ${CHUNK_OVERLAP:50}
    max-chunks-per-query: ${MAX_CHUNKS_PER_QUERY:5}
    similarity-threshold: 0.3
  
  # File storage configuration
  storage:
    upload-dir: ${UPLOAD_DIR:./uploads}
    allowed-types: ${ALLOWED_FILE_TYPES:pdf}
    max-file-size: ${MAX_FILE_SIZE:10485760}  # 10MB in bytes
  
  # Router configuration
  router:
    keywords:
      rag: document,policy,manual,guide,regulation,clause,instruction
      nlp: what is,how,why,explain,define

# Logging configuration
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.scb.ragdemo: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/scb-rag-demo.log
    max-size: 10MB
    max-history: 30
